### ISSUE TITLE
Launch error with "Vysor binary was not found at" on Windows with Vysor 4.1.77 installed

### ISSUE THREAD

**Issue by AnyOfYou** [koush/vysor-cli#1]
I have been installed Vysor-win-4.1.77 before use vysor-cli.

Got "Vysor binary was not found at C:\Users\Admin\Local\Vysor\Vysor.exe" error.
The vysor binary on my PC (Windows 10) is located on C:\Users\Admin\AppData\Local\vysor\Vysor.exe.

Also I have look at the code on vysor-cli's cli.ts, I try to launch Vysor with Vysor.exe --args -s DEVICE_SN, but vysor still start normally. I except that could be launch vysor screen with the device connected.

**Comment by asheroto** [comment]
Same problem here. It's looking at the wrong path, it's missing AppData.

I created a symbolic link from `C:\Users\User\Local\Vysor` to `C:\Users\User\AppData\Local\Vysor` and it now launches, but using `vysor --s DEVICE_SN` it just launches the main Vysor screen and not the device itself.

**Comment by asheroto** [comment]
Oddly enough, if I type `vywsor -d` it launches the remote control screen to my Android.

**Comment by asheroto** [comment]
I created a PR that [fixes the path](https://github.com/koush/vysor-cli/pull/2).

**Comment by koush** [comment]
Resolved and published thank you

**Comment by asheroto** [comment]
😊 thank you

**Comment by asheroto** [comment]
Hello,

Just noticed that the npm package is still pointing to the wrong folder location.

Installed using

```
npm -g install vysor
```

![image](https://github.com/koush/vysor-cli/assets/49938263/97d30269-b9d5-4c3a-9d45-283e34116db1)

As you can see, it's missing AppData.

It should be...

`C:\Users\<username>\AppData\Local\Vysor\Vysor.exe`

Looks like the GitHub repo is updated, but not the npm repo.
